name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - main  # or master, or whichever branch you want to auto-deploy from

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm install  # or yarn install if you're using Yarn

    - name: Build
      run: npm run build  # or your build script

    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}